package CalcApp;


/**
* CalcApp/Calc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcApp.idl
* Monday, 1 April, 2024 4:43:46 PM IST
*/

public interface Calc extends CalcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calc
